version: '3.3'
services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongodb:
      image: mongo:4.2
      container_name: mongodb
      user: 1000:1000
      volumes:
        #- mongo_data:/data/db
        - /Data/graylog-mongo:/data/db
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
      ports:
        -  27017:27017
      # networks:
      #   - graylog

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      container_name: elasticsearch
      user: 1000:1000
      volumes:
        - es_data:/usr/share/elasticsearch/data
        - /Data/graylog-docker-single/elasticsearch/conf/elasticsearch.yml:/usr/share/elasticsearch/conf/elasticsearch.yml
        #- /Data/graylog-elasticsearch/data:/usr/share/elasticsearch/data
      # - /Data/graylog-elasticsearch:/usr/share/elasticsearch/logs
      environment:
        - cluster.name=elasticsearch
        #- http.host=0.0.0.0
        #- transport.host=127.0.0.1
        #- network.host=0.0.0.0:ipv4_
        - discovery.type=single-node
        - node.name=node-1
        - bootstrap.memory_lock=true
        #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        -  "ES_JAVA_OPTS=-Djava.net.preferIPv4Stack=true -Dlog4j2.formatMsgNoLookups=true -Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
            soft: 65536
            hard: 65536
      ports:
        - 9200:9200
        - 9300:9300
      # networks:
      #   - graylog
      #mem_limit: 1g
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.2
      container_name: graylog
      user:  graylog:graylog
      volumes:
        - /Data/graylog-docker-single/graylog/config/graylog.conf:/usr/share/graylog/data/config/graylog.conf
        - graylog_data:/usr/share/graylog/data
        - /Data/graylog-docker-single/graylog/plugin:/usr/share/graylog/plugin
        - /Data/graylog-docker-single/graylog/plugin/graylog-plugin-telegram-notification-2.3.7.jar:/usr/share/graylog/plugin/graylog-plugin-telegram-notification-2.3.7.jar
      environment:
        - GRAYLOG_PLUGIN_DIR=/Data/graylog-docker-single/graylog/plugin
        - GRAYLOG_ELASTICSEARCH_VERSION=7
        - GRAYLOG_WEB_ENDPOINT_URI=http://172.16.99.201:9000/api
        # CHANGE ME (must be at least 16 characters)!
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        # Password: admin
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://172.16.99.201:9000/
        - GRAYLOG_ROOT_TIMEZONE=Asia/Taipei
      #- GRAYLOG_MONGODB_URI=mongodb://admin:1234567890@localhost:27017/graylog
        - GRAYLOG_MONGODB_URI=mongodb://172.16.99.201:27017/graylog
      #entrypoint: /usr/bin/tini -- wait-for-it 172.16.99.201:9200 --  /docker-entrypoint.sh
      networks:
        - graylog
      links:
         - mongodb:mongo
         - elasticsearch
      restart: always
      depends_on:
        - mongodb
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 1514:1514
        # Syslog UDP
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp
        - 12202:12202
networks:
    graylog:
      driver: bridge
  # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
#   mongo_data:
#     driver: local
   es_data:
     driver: local
   graylog_data:
     driver: local

